spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/rendicontation/protocol/openiid-connect/certs
          issuer-uri: http://localhost:8080/auth/realms/rendicontation